#!/bin/bash
# BF16修复环境变量设置脚本

export PYTORCH_ENABLE_MPS_FALLBACK=1
export PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
export TOKENIZERS_PARALLELISM=false
export TRANSFORMERS_OFFLINE=0

echo "✓ BF16修复环境变量已设置"
echo "  PYTORCH_ENABLE_MPS_FALLBACK=$PYTORCH_ENABLE_MPS_FALLBACK"
echo "  PYTORCH_MPS_HIGH_WATERMARK_RATIO=$PYTORCH_MPS_HIGH_WATERMARK_RATIO"
echo "  TOKENIZERS_PARALLELISM=$TOKENIZERS_PARALLELISM"
